import type { Question } from '../types';

export const quizQuestions: Question[] = [
  // Chemistry
  {
    id: 1,
    category: 'Chemistry',
    question: 'A compound is found to contain 40.0% Carbon, 6.7% Hydrogen, and 53.3% Oxygen by mass. If its molar mass is approximately 180 g/mol, what is its molecular formula? (Atomic masses: C=12, H=1, O=16)',
    options: { a: 'CH₂O', b: 'C₂H₄O₂', c: 'C₃H₆O₃', d: 'C₆H₁₂O₆' },
    correctAnswer: 'd',
  },
  {
    id: 2,
    category: 'Chemistry',
    question: 'What is the molarity of a solution prepared by dissolving 4.9 g of H₂SO₄ in enough water to make 250 mL of solution? (Atomic masses: H=1, S=32, O=16)',
    options: { a: '0.1 M', b: '0.05 M', c: '0.2 M', d: '0.4 M' },
    correctAnswer: 'c',
  },
   {
    id: 3,
    category: 'Chemistry',
    question: 'Given that the proton number of an atom is 17, which of the following represents its electronic configuration?',
    options: { a: '1s²2s²2p⁶3s²3p⁵', b: '1s²2s²2p⁶3s²3p⁶', c: '1s²2s²2p⁶3s²3d⁵', d: '[Ne] 3s²3p⁴' },
    correctAnswer: 'a',
  },
  {
    id: 4,
    category: 'Chemistry',
    question: 'Using the Valence Shell Electron Pair Repulsion (VSEPR) theory, predict the shape of the NH₃ molecule and its approximate bond angle.',
    options: { a: 'Trigonal planar, 120°', b: 'Tetrahedral, 109.5°', c: 'Linear, 180°', d: 'Trigonal pyramidal, 107°' },
    correctAnswer: 'd',
  },
  {
    id: 5,
    category: 'Chemistry',
    question: 'In the reaction 2MnO₄⁻ + 5C₂O₄²⁻ + 16H⁺ → 2Mn²⁺ + 10CO₂ + 8H₂O, what is the change in the oxidation number of manganese?',
    options: { a: 'From +2 to +7', b: 'From +4 to +2', c: 'From +6 to +2', d: 'From +7 to +2' },
    correctAnswer: 'd',
  },
  {
    id: 6,
    category: 'Chemistry',
    question: 'Given the enthalpy of formation (NaCl) = -411 kJ/mol, and other relevant Born-Haber cycle components sum to +375 kJ/mol (sublimation, dissociation, ionization, electron affinity), calculate the lattice energy of NaCl.',
    options: { a: '+786 kJ/mol', b: '+36 kJ/mol', c: '-786 kJ/mol', d: '-36 kJ/mol' },
    correctAnswer: 'c',
  },
  {
    id: 7,
    category: 'Chemistry',
    question: 'A first-order reaction has a half-life of 20 seconds. What is the rate constant for this reaction?',
    options: { a: '0.03465 s⁻¹', b: '0.0347 s⁻¹', c: '0.05 s⁻¹', d: '0.0461 s⁻¹' },
    correctAnswer: 'b',
  },
  {
    id: 8,
    category: 'Chemistry',
    question: 'For the reaction A + B ⇌ C, at equilibrium, the concentrations are [A] = 0.1 M, [B] = 0.2 M, and [C] = 0.4 M. Calculate the equilibrium constant, Kc.',
    options: { a: '2', b: '8', c: '0.08', d: '20' },
    correctAnswer: 'd',
  },
  {
    id: 9,
    category: 'Chemistry',
    question: 'A radioactive isotope has a half-life of 5 years. How long will it take for 75% of a sample of this isotope to decay?',
    options: { a: '5 years', b: '7.5 years', c: '10 years', d: '15 years' },
    correctAnswer: 'c',
  },
  {
    id: 10,
    category: 'Chemistry',
    question: 'A student measures the mass of a substance as 15.2 g. The actual mass is 15.0 g. Calculate the percentage relative error of the measurement.',
    options: { a: '0.2%', b: '1.33%', c: '2.0%', d: '0.13%' },
    correctAnswer: 'b',
  },
  // Mathematics
  {
    id: 11,
    category: 'Mathematics',
    question: 'What is the sum to infinity of the geometric progression: 9, 3, 1, ...?',
    options: { a: '12', b: '13.5', c: '18', d: '27' },
    correctAnswer: 'b',
  },
  {
    id: 12,
    category: 'Mathematics',
    question: 'Solve the following system of linear equations using matrix methods:\nx + y = 5\n2x - y = 1',
    options: { a: 'x=1, y=4', b: 'x=3, y=2', c: 'x=4, y=1', d: 'x=2, y=3' },
    correctAnswer: 'd',
  },
  {
    id: 13,
    category: 'Mathematics',
    question: 'Evaluate (cos(π/6) + i sin(π/6))⁶ using De-Moivre\'s Theorem.',
    options: { a: '1/2 + i√3/2', b: '-1/2 + i√3/2', c: '-1', d: '1' },
    correctAnswer: 'c',
  },
  {
    id: 14,
    category: 'Mathematics',
    question: 'Find the x-coordinate of the local maximum of the function f(x) = x³ - 3x² + 2.',
    options: { a: 'x = 2', b: 'x = 0', c: 'x = 1', d: 'x = -1' },
    correctAnswer: 'b',
  },
  {
    id: 15,
    category: 'Mathematics',
    question: 'Calculate the area under the curve y = x² from x = 0 to x = 3.',
    options: { a: '3 units²', b: '6 units²', c: '9 units²', d: '12 units²' },
    correctAnswer: 'c',
  },
  {
    id: 16,
    category: 'Mathematics',
    question: 'Find the general solution to the differential equation dy/dx = 2x.',
    options: { a: 'y = 2x + C', b: 'y = x²/2 + C', c: 'y = x² + C', d: 'y = 2 + C' },
    correctAnswer: 'c',
  },
  {
    id: 17,
    category: 'Mathematics',
    question: 'For the data set {2, 4, 6, 8}, calculate the standard deviation.',
    options: { a: '1.58', b: '2.24', c: '2.5', d: '4' },
    correctAnswer: 'b',
  },
  {
    id: 18,
    category: 'Mathematics',
    question: 'A committee of 3 people is to be selected from a group of 5 men and 4 women. How many different committees can be formed that consist of 2 men and 1 woman?',
    options: { a: '20', b: '40', c: '50', d: '60' },
    correctAnswer: 'b',
  },
  {
    id: 19,
    category: 'Mathematics',
    question: 'A projectile is launched horizontally from a cliff 45 m high with an initial speed of 20 m/s. How far from the base of the cliff does it land? (Assume g = 10 m/s²)',
    options: { a: '30 m', b: '40 m', c: '50 m', d: '60 m' },
    correctAnswer: 'd',
  },
  {
    id: 20,
    category: 'Mathematics',
    question: 'If £1,000 is invested at an annual interest rate of 5% compounded annually, what will be the value of the investment after 3 years?',
    options: { a: '£1,102.50', b: '£1,157.63', c: '£1,150.00', d: '£1,215.51' },
    correctAnswer: 'b',
  },
  // Physics
  {
    id: 21,
    category: 'Physics',
    question: 'A stone is thrown vertically upwards with an initial velocity of 20 m/s from the ground. How long does it take to reach its maximum height? (Assume g = 10 m/s²)',
    options: { a: '1 s', b: '2 s', c: '3 s', d: '4 s' },
    correctAnswer: 'b',
  },
  {
    id: 22,
    category: 'Physics',
    question: 'A 2 kg mass moving at 5 m/s collides with a stationary 3 kg mass. If they stick together after the collision, what is their common velocity?',
    options: { a: '1 m/s', b: '2 m/s', c: '3 m/s', d: '4 m/s' },
    correctAnswer: 'b',
  },
  {
    id: 23,
    category: 'Physics',
    question: 'A pump lifts 500 kg of water to a height of 10 m in 20 seconds. Calculate the power of the pump. (Assume g = 10 m/s²)',
    options: { a: '1000 W', b: '2000 W', c: '2500 W', d: '5000 W' },
    correctAnswer: 'c',
  },
  {
    id: 24,
    category: 'Physics',
    question: 'A mass attached to a spring oscillates with a period of 2 seconds. If the mass is quadrupled, what will be the new period of oscillation?',
    options: { a: '1 s', b: '2 s', c: '4 s', d: '8 s' },
    correctAnswer: 'c',
  },
  {
    id: 25,
    category: 'Physics',
    question: 'What volume will 2 moles of an ideal gas occupy at 27°C and a pressure of 2 atm? (R = 0.0821 L·atm/(mol·K))',
    options: { a: '12.3 L', b: '24.6 L', c: '24.63 L', d: '49.2 L' },
    correctAnswer: 'c',
  },
  {
    id: 26,
    category: 'Physics',
    question: 'How much heat energy is required to raise the temperature of 500 g of water from 20°C to 80°C? (Specific heat capacity of water = 4.2 J/g°C)',
    options: { a: '105,000 J', b: '126,000 J', c: '126 kJ', d: '252 kJ' },
    correctAnswer: 'c',
  },
  {
    id: 27,
    category: 'Physics',
    question: 'A heater with a resistance of 20 Ω is connected to a 240 V supply. Calculate the power dissipated by the heater.',
    options: { a: '1440 W', b: '2000 W', c: '2880 W', d: '5760 W' },
    correctAnswer: 'c',
  },
  {
    id: 28,
    category: 'Physics',
    question: 'A 10 μF capacitor is charged to a potential difference of 100 V. How much energy is stored in the capacitor?',
    options: { a: '0.01 J', b: '0.05 J', c: '0.05 J', d: '0.1 J' },
    correctAnswer: 'c',
  },
  {
    id: 29,
    category: 'Physics',
    question: 'If a radioactive sample initially has 800 atoms, and after 30 minutes, 200 atoms remain, what is the half-life of the sample?',
    options: { a: '5 minutes', b: '10 minutes', c: '15 minutes', d: '20 minutes' },
    correctAnswer: 'c',
  },
  {
    id: 30,
    category: 'Physics',
    question: 'A photon with an energy of 5.0 eV strikes a metal surface with a work function of 3.0 eV. What is the maximum kinetic energy of the emitted photoelectron?',
    options: { a: '8.0 eV', b: '3.0 eV', c: '2.0 eV', d: '5.0 eV' },
    correctAnswer: 'c',
  },
  // English
  {
    id: 31,
    category: 'English',
    question: 'Jane with her husband __________ here now.',
    options: { a: 'are', b: 'were', c: 'is', d: 'have been' },
    correctAnswer: 'c',
  },
  {
    id: 32,
    category: 'English',
    question: 'The Principal and the English teacher __________ kind.',
    options: { a: 'is', b: 'was', c: 'are', d: 'has been' },
    correctAnswer: 'c',
  },
  {
    id: 33,
    category: 'English',
    question: 'Neither the men nor the boy __________ here now.',
    options: { a: 'are', b: 'were', c: 'is', d: 'have been' },
    correctAnswer: 'c',
  },
  {
    id: 34,
    category: 'English',
    question: 'Mr Japhet is one of the teachers who __________ in my school.',
    options: { a: 'teaches', b: 'has taught', c: 'teach', d: 'taught' },
    correctAnswer: 'c',
  },
  {
    id: 35,
    category: 'English',
    question: 'One of my teachers __________ coming.',
    options: { a: 'are', b: 'were', c: 'is', d: 'have been' },
    correctAnswer: 'c',
  },
  {
    id: 36,
    category: 'English',
    question: 'The poor __________ in misery.',
    options: { a: 'lives', b: 'lived', c: 'has lived', d: 'live' },
    correctAnswer: 'd',
  },
  {
    id: 37,
    category: 'English',
    question: 'A number of students __________ missed the opportunity to register.',
    options: { a: 'is', b: 'has', c: 'have', d: 'does' },
    correctAnswer: 'c',
  },
  {
    id: 38,
    category: 'English',
    question: 'My scissors __________ a replacement.',
    options: { a: 'needs', b: 'needed', c: 'need', d: 'has needed' },
    correctAnswer: 'c',
  },
  {
    id: 39,
    category: 'English',
    question: 'Mathematics __________ difficult for Arts students.',
    options: { a: 'seem', b: 'seeming', c: 'seems', d: 'were seeming' },
    correctAnswer: 'c',
  },
  {
    id: 40,
    category: 'English',
    question: 'The committee __________ submitted its report.',
    options: { a: 'are', b: 'were', c: 'has', d: 'have' },
    correctAnswer: 'c',
  },
];
